- name: remove pre-existing k8s directory for master
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ k8s_etc_dir }}"
    - "{{ k8s_config_dir }}"
    - "{{ k8s_var_lib }}"
  become: yes

- name: disable kube-apiserver, kube-scheduler and kube-controller-manager services for masters
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
  become: yes

- name: remove systemctl config files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ systemd_service_dir }}/kube-apiserver.service"
    - "{{ systemd_service_dir }}/kube-controller-manager.service"
    - "{{ systemd_service_dir }}/kube-scheduler.service"
  become: yes
