- name: pull the docker image that contain all necessary files for installation
  command: docker pull codemk8/ksbins:1.11.0
#  register: todo

#- debug: msg="{{ todo.stdout }}"
#- debug: msg="{{ todo.stderr }}"

- name: create a local depot directory to store files
  file:
    path: "{{local_depot_dir}}"
    state: directory

- name: copy files from docker image to local depot dir
  shell: |
    docker ps -a # a simple run
    docker run --rm --name ksbin_temp codemk8/ksbins:1.11.0
    docker cp ksbin_temp:/ks-eco/binaries/etcdctl "{{local_depot_dir}}"/.
    docker cp ksbin_temp:/ks-eco/binaries/etcd "{{local_depot_dir}}"/.
    docker cp ksbin_temp:/ks-eco/binaries/hyperkube "{{local_depot_dir}}"/.
    docker rm -f ksbin_temp
