---

- name: sanity check all hosts
  hosts: all
  gather_facts: False
  roles:
    - role: check

#- name: Prepare required files on localhost
#  hosts: local
#  roles:
#    - role: download

#- name: Copy files to all nodes
#  hosts: k8s-all
#  gather_facts: False
#  roles:
#    - role: prepare

- name: Set up etcd 
  hosts: etcd
  gather_facts: False
  roles:
    - role: etcd    