---

- name: sanity check all hosts
  hosts: all
  gather_facts: False
  roles:
    - check

- name: Prepare required files on localhost
  hosts: deploy
  roles:
#    - download
    - gen_certs

#- name: Copy files to all nodes
#  hosts: k8s-all
#  gather_facts: False
#  roles:
#    - role: prepare

- name: Set up etcd
  hosts: etcd
  gather_facts: False
  roles:
   - role: etcd

- name: setup k8s master
  hosts: k8s-master
  gather_facts: False 
  roles:
    - role: master

#- name: setup k8s worker
#  hosts: k8s-worker
#  gather_facts: False
#  roles:
#    - role: worker
