---

- name: sanity check all hosts
  hosts: all
  gather_facts: False
  roles:
    - check

- name: Prepare required files on localhost
  hosts: deploy
  roles:
    - download
    - gen_certs

#- name: Copy files to all nodes
#  hosts: k8s-all
#  gather_facts: False
#  roles:
#    - role: prepare

- name: Set up etcd
  hosts: etcd
  gather_facts: False
  roles:
   - role: etcd
