- name: create etcd directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ etcd_root }}"
    - "{{ etcd_ssl_dir }}"
    - "{{ etcd_var_data_dir }}"
  become: yes

- name: copy etcd binaries to etcd dir
  copy:
    src: "{{ local_depot_dir }}/{{ item }}"
    dest: "{{ etcd_root }}"
    mode: 0755
  with_items:
    - etcd
    - etcdctl
  become: yes

- name: enable etcd server port
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 2380/tcp

- name: copy etcd ssl files
  copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ etcd_ssl_dir }}"
  with_items:
    - etcd.pem
    - etcd-key.pem
    - ca.pem
  become: yes
  notify:
    - "restart etcd service"

- name: generate etcd service file
  template:
    src: etcd.service.j2
    dest: "{{ systemd_service_dir }}/etcd.service"
  become: yes
  notify:
    - "restart etcd service"

#  TODO: check status
#etcdctl --key-file=/tmp/ksgpu/certs/etcd name=ks-01 \
# peerURLs=https://192.168.1.6:2380 clientURLs=https://192.168.1.6:...