- name: create k8s directory for worker
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ kubelet_var_dir }}"
    - "{{ kube_proxy_var_dir }}"
  become: yes

- name: copy ssl files
  copy:
    src: "{{ local_certs_dir }}/{{inventory_hostname}}/{{item}}"
    dest: "{{ kubelet_var_dir }}"
  with_items:
    - "{{inventory_hostname}}-key.pem"
    - "{{inventory_hostname}}.pem"    
  become: yes
  
- name: generate kubelet service file
  template:
    src: kubelet.service.j2
    dest: "{{ systemd_service_dir }}/kubelet.service"
  become: yes
  notify:
    - "restart kubelet service"

- name: generate kube-proxy service file
  template:
    src: kube-proxy.service.j2
    dest: "{{ systemd_service_dir }}/kube-proxy.service"
  become: yes
  notify:
    - "restart kube-proxy service"
