- name: create k8s directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ k8s_etc_dir }}"
    - "{{ k8s_ssl_dir }}"
  become: yes

- name: copy k8s apiserver ssl files
  copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ k8s_ssl_dir }}"
  with_items:
    - kubernetes.pem
    - kubernetes-key.pem
    - ca.pem
    - ca-key.pem
  become: yes
  notify:
    - "restart kube-apiserver service"

- name: generate k8s-apiserver service file
  template:
    src: kube-apiserver.service.j2
    dest: "{{ systemd_service_dir }}/kube-apiserver.service"
  become: yes
  notify:
    - "restart kube-apiserver service"

- name: generate k8s-controller-manager service file
  template:
    src: kube-controller-manager.service.j2
    dest: "{{ systemd_service_dir }}/kube-controller-manager.service"
  become: yes
  notify:
    - "restart kube-controller-manager service"

- name: generate k8s-scheduler service file
  template:
    src: kube-scheduler.service.j2
    dest: "{{ systemd_service_dir }}/kube-scheduler.service"
  become: yes
  notify:
    - "restart kube-scheduler service"
