- name: remove pre-existing k8s directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ k8s_etc_dir }}"
    - "{{ k8s_config_dir }}"
    - "{{ k8s_var_lib }}"
  become: yes

- name: create k8s directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ k8s_etc_dir }}"
    - "{{ k8s_config_dir }}"
    - "{{ k8s_var_lib }}"
  become: yes


- name: enable master api server port in 
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 6443/tcp
  become: yes

- name: copy k8s apiserver ssl files
  copy:
    src: "{{ local_certs_dir }}/{{ item }}"
    dest: "{{ k8s_var_lib }}"
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes.pem
    - kubernetes-key.pem
    - service-account-key.pem 
    - service-account.pem 
    - kube-controller-manager.kubeconfig
    - kube-scheduler.kubeconfig
    - etcd.pem
    - etcd-key.pem
  become: yes
  notify:
    - "restart kube-apiserver service"

- name: generate k8s-apiserver service file
  template:
    src: kube-apiserver.service.j2
    dest: "{{ systemd_service_dir }}/kube-apiserver.service"
  become: yes
  notify:
    - "restart kube-apiserver service"

- name: generate k8s-scheduler yaml file
  template:
    src: kube-scheduler.yaml.j2
    dest: "{{ k8s_config_dir }}/kube-scheduler.yaml"
  become: yes
  notify:
    - "restart kube-scheduler service"

- name: generate k8s-controller-manager service file
  template:
    src: kube-controller-manager.service.j2
    dest: "{{ systemd_service_dir }}/kube-controller-manager.service"
  become: yes
  notify:
    - "restart kube-controller-manager service"

- name: generate k8s-scheduler service file
  template:
    src: kube-scheduler.service.j2
    dest: "{{ systemd_service_dir }}/kube-scheduler.service"
  become: yes
  notify:
    - "restart kube-scheduler service"
